### ISSUE TITLE
Consider Ghizmo

### ISSUE THREAD

**Issue by jlevy** [fffaraz/awesome-github#4]
Thanks for the nice list!

Shameless mention of a hack of my own that may be of interest:
[Ghizmo](https://github.com/jlevy/ghizmo) is a sort of missing command line for GitHub that gives access to _all_ the GitHub APIs (such as for contributors, pull requests, releases, etc., beyond what hub gives). Input and output via JSON, for compatibility with jq.

Would be glad for feedback, contributions, and/or considering it for inclusion.

**Comment by fffaraz** [comment]
Hey, Just send me a pull request so that I can merge that into the list.
